version: '2'
services:
    rcb-app:
        image: rcb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rcb-mysql:3306/rcb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rcb-mysql:
        extends:
            file: mysql.yml
            service: rcb-mysql
